require:
  - rubocop-rake

AllCops:
  TargetRubyVersion: <%= ruby_version %>
  Exclude:
    - node_modules/**/*
    - layers/dependencies/ruby/**/*

Layout/ClosingParenthesisIndentation:
  Enabled: false
Layout/LineLength:
  Max: 200
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: false

Lint/Debugger:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Exclude:
    - 'Gemfile'

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
